# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('ID', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('AppName', models.CharField(max_length=40)),
                ('URL', models.CharField(max_length=100)),
                ('IDC', models.CharField(max_length=3)),
                ('Alarmtype', models.CharField(max_length=8)),
                ('Alarmconditions', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('ID', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('FID', models.SmallIntegerField()),
                ('NAMELOOKUP_TIME', models.FloatField()),
                ('CONNECT_TIME', models.FloatField()),
                ('PRETRANSFER_TIME', models.FloatField()),
                ('STARTTRANSFER_TIME', models.FloatField()),
                ('TOTAL_TIME', models.FloatField()),
                ('HTTP_CODE', models.CharField(max_length=100)),
                ('SIZE_DOWNLOAD', models.FloatField()),
                ('HEADER_SIZE', models.SmallIntegerField()),
                ('REQUEST_SIZE', models.SmallIntegerField()),
                ('CONTENT_LENGTH_DOWNLOAD', models.FloatField()),
                ('SPEED_DOWNLOAD', models.FloatField()),
                ('DATETIME', models.IntegerField()),
                ('MARK', models.CharField(max_length=1)),
            ],
        ),
    ]
